project:
  type: website
  render:
    - /slides/introduction.qmd
    - /slides/wrangling.qmd
    - /slides/stats.qmd
    - /slides/ggplot.qmd
    - /slides/geospatial.qmd
    - /slides/cartography.qmd
    - /slides/quarto.qmd
    - index.qmd
    - utils/report.qmd
    - "/cards/**/*.qmd"
    - "/exercises/**/*.qmd"
  resources:
    - "CNAME"

website:
  title: "Introduction to quantitative methods with {{< fa brands r-project >}}"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: exercises/r-base.html
        text: Introduction
      - text: "Manipulate data"
        menu:
          - exercises/r-wrangling.qmd
          - exercises/geospatial-wrangling.qmd
      - text: "Visualize"
        menu:
          - exercises/ggplot.qmd
          - exercises/cartography.qmd
      - text: "Communicate"
        menu:
          - exercises/quarto.qmd
      - text: "Evaluation"
        menu:
          - exercises/eval.qmd
      - icon: github
        href: https://github.com/linogaliana/r-geographie
    background: "#802a03"
  twitter-card:
    image: /cards/version-light/baby.png

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-annotations: hover
    code-link: true
    emoji: true

author: Clara Baudry, Nathan Randriamanana



#knitr:
#  opts_chunk:
#    out.width: "90%"

